name: ai_pipeline_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  pdf: ^3.10.8
  intl: ^0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  camera: ^0.11.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
